- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
              if [ `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp-trainschedule | wc -l` -gt 0 ]; then  
            kubectl delete deploy `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp-trainschedule`
         else 
            echo "No app deployments found"
         fi
         if [ `kubectl get svc | grep myapp-trainschedule-svc  | awk '{print $1}' | wc -l` -gt 0 ]; then
            kubectl delete svc `kubectl get svc | grep myapp-trainschedule-svc | awk '{print $1}'`
         else
            echo "No app service found"
         fi
    - name: deploy app
      shell: kubectl create deploy myapp-trainschedule --image=nalkhande/trainschedule:{{ build }}
    - name: increase replicas 
      shell: kubectl scale deploy myapp-trainschedule --replicas=2
    - name: deploy service
      shell: kubectl expose deploy myapp-trainschedule --name myapp-trainschedule-svc --port 8080 --type NodePort

